### ISSUE TITLE
Error Launching GuitarSniffer

### ISSUE THREAD

**Issue by B0rb-0G** [artman41/FenderStratocastorSniffer#8]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PcapDotNet.Core.dll' or one of its dependencies. The specified module could not be found.
   at GuitarSniffer.PacketSniffer.Start()
   at GuitarSniffer.Program.Start() in C:\Users\Tyler\RiderProjects\FenderStratocastorSniffer\GuitarSniffer\Program.cs:line 16
   at GuitarSniffer.Program.Main(String[] args) in C:\Users\Tyler\RiderProjects\FenderStratocastorSniffer\GuitarSniffer\Program.cs:line 11

- I do not have a user called Tyler in my system....

**Comment by B0rb-0G** [comment]
I have all the drivers installed correctly. I even reinstalled all of them.

**Comment by B0rb-0G** [comment]
I fixed the problem on my windows 10 computer. All I did was install python with PIP.

**Comment by Poriah64** [comment]
Hi Dakotastar1055.
Which files did you install to get the Guitar Sniffer to work? I installed the Win and USBpcap along with the most recent version of the sniffer but I get nothing. I have the XB1 dongle and Strat paired.
